# Generated by Django 4.1.7 on 2023-03-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
